// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Doctor: typeof import('./components/Sk/Doctor.vue')['default']
    DoctorHome: typeof import('./components/Sk/DoctorHome.vue')['default']
    Hpvlist: typeof import('./components/Sk/Hpvlist.vue')['default']
    Nucleic: typeof import('./components/Sk/Nucleic.vue')['default']
    PhyDetails: typeof import('./components/Sk/PhyDetails.vue')['default']
    PhyExam: typeof import('./components/Sk/PhyExam.vue')['default']
    Point: typeof import('./components/Point.vue')['default']
    PopUps: typeof import('./components/PopUps.vue')['default']
    Prompt: typeof import('./components/Prompt.vue')['default']
    Registered: typeof import('./components/Sk/Registered.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelfTest: typeof import('./components/Sk/SelfTest.vue')['default']
    SeMember: typeof import('./components/SeMember.vue')['default']
    SkIndex: typeof import('./components/Sk/SkIndex.vue')['default']
    SlefTestResult: typeof import('./components/Sk/SlefTestResult.vue')['default']
  }
}
